/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{

  GtkWidget *Gestion_Restau;
 GtkWidget *Gestion_Capteur;
 GtkWidget *acceuilw;
  GtkWidget *gestionw;
 GtkWidget *servp2; 
     GtkWidget  *afficher_et;
GtkWidget *window_stock;






#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");
  add_pixmap_directory ("../photo");
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */


 
  Gestion_Restau = create_Gestion_Restau ();
  gtk_widget_show (Gestion_Restau);

Gestion_Capteur = create_Gestion_Capteur();
  gtk_widget_show (Gestion_Capteur);

   acceuilw = create_acceuilw ();
  gtk_widget_show (acceuilw);

 afficher_et = create_afficher_et ();
  gtk_widget_show (afficher_et);

window_stock = create_window_stock();
  gtk_widget_show (window_stock);
  gtk_main ();
  return 0;
}

